---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: beapizer
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: beapizer
  name: beapizer-config
data:
  API_ROOT_RESOURCE_PATH: /beapizer/api/v1
  DS_DIALECT: "mongodb"
  DS_URL: "mongodb+srv://<DB_USER>:<DB_PASSWORD>@<DB_CLUSTER>/<DB>?retryWrites=true&w=majority"
  NODE_ENV: producti<DB> "3333"
  MAX_PAGE_SIZE: "200"
  SERVER_TIMEOUT: "20000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beapizer
  labels:
    name: beapizer
  name: beapizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beapizer
      type: generic-api
  strategy: {}
  template:
    metadata:
      labels:
        app: beapizer
        type: generic-api
    spec:
      containers:
        - name: beapizer
          image: localhost/beapizer:1.0.0
          imagePullPolicy: IfNotPresent
          command:
          - /bin/sh
          - -c
          - 'npm run startproduction | tee /var/log/beapizer.log'
          envFrom:
          - configMapRef:
              name: beapizer-config
          volumeMounts:
            - name: log-volume
              mountPath: "/var/log"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: log-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: beapizer
  labels:
    app: beapizer
    type: generic-api
  name: beapizer-cluster-srv
spec:
  ports:
  - port: 8881
    protocol: TCP
    targetPort: 3333
  selector:
    app: beapizer
  type: ClusterIP
---

