---
apiVersion: v1
kind: Namespace
metadata:
  name: beapizer
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: beapizer
  name: beapizer-config
data:
  API_ROOT_RESOURCE_PATH: /myapi/v1.0
  DS_DIALECT: "mongodb"
  DS_URL: "mongodb+srv://<DB_USER>:<DB_PASSWORD>@<DB_CLUSTER>/<DB>?retryWrites=true&w=majority"
  NODE_ENV: producti<DB> "3333"
  MAX_PAGE_SIZE: "200"
  SERVER_TIMEOUT: "20000"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/log/beapizer"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pv-claim
  namespace: beapizer
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beapizer
  labels:
    name: beapizer
  name: beapizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beapizer
      type: generic-api
  strategy: {}
  template:
    metadata:
      labels:
        app: beapizer
        type: generic-api
    spec:
      containers:
        - name: beapizer
          image: localhost/beapizer:0.1.1
          imagePullPolicy: IfNotPresent
          command:
          - /bin/sh
          - -c
          - 'npm run beapizer | tee /var/log/beapizer.log'
          envFrom:
          - configMapRef:
              name: beapizer-config
          volumeMounts:
            - name: log-volume
              mountPath: "/var/log"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: beapizer
  labels:
    app: beapizer
    type: generic-api
  name: beapizer-cluster-srv
spec:
  ports:
  - port: 8881
    protocol: TCP
    targetPort: 3333
  selector:
    app: beapizer
  type: ClusterIP
---

